### ISSUE TITLE
Shuffle playback does not auto-advance through the play queue correctly

### ISSUE THREAD

**Issue by watkins-matt** [UnicornsOnLSD/finamp#243]
While playing songs in shuffle mode, if you let a song finish playing it will never go to the correct next song in the shuffle queue. 

Otherwise everything works with shuffle off or when you press the next song button.

This bug can be really annoying because if I start skipping songs after a song finished playing, I may end up seeing the exact same song that just played after a few skips instead of having to go through the entire playlist.

Reproduced on both a phone and Android emulator. Steps to reproduce:

1. Open a playlist, put it in shuffle mode and start playing.
2. Press the button to look at the play queue, make note of what the next song should be in the play queue.
3. Press the seek bar near the end of the currently playing song (maybe a few seconds before it ends) and let the song finish playing; do not hit the next button
4. The new song that is playing is not the correct song that was identified as the next song in the play queue from step 2.

**Comment by UnicornsOnLSD** [comment]
That's odd, looking into it now

**Comment by UnicornsOnLSD** [comment]
Fixed in 09ae80f

**Comment by watkins-matt** [comment]
Awesome, that was fast! I pulled the new code to test it out and it looks like this does fix the scenario posted. 

I noticed that if you go back to the playlist and press the Shuffle button to start playback on that screen first (the one with text next to the "Play" button) it seems like the same issue still occurs though.

**Comment by UnicornsOnLSD** [comment]
I can't reproduce that on iOS, I'll check on Android tomorrow :)

**Comment by UnicornsOnLSD** [comment]
Fixed in a6c2ac1
